apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastify-url-shortner
  name: nginx-deployment-web
  namespace: int
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        name: fastify-url-shortner
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastify-url-shortner-web
  namespace: int
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fastify-url-shortner
  type: ClusterIP
