apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastify-url-shortner
    foo: bar
  name: nginx-deployment
  namespace: int
spec:
  replicas: 19
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.27.4
        name: main
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastify-url-shortner
  namespace: int
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fastify-url-shortner
  type: ClusterIP
