apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastify-url-shortner
    foo: bar
  name: nginx-deployment
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: ghcr.io/whereismyjetpack/url-shortener:1c77616a1092268608ba6d0523d54ca25bb6e39f
        name: fastify-url-shortner
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastify-url-shortner
  namespace: staging
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fastify-url-shortner
  type: ClusterIP
