---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: "{{ kargo_project_name }}"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: {{ kargo_project_name }}
  namepsace: {{ kargo_project_name }}
spec:
  promotionPolicies:
  - stageSelector:
      name: "glob:integration*"
    autoPromotionEnabled: true
  - stageSelector:
      name: "glob:staging*"
    autoPromotionEnabled: true
  - stageSelector:
      name: "glob:production*"
    autoPromotionEnabled: false
