---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-deployment
  labels:
    app: fastify-url-shortner
    foo: bar
spec:
  strategy:
    blue-green:
      activeService: fastify-url-shortner
      previewService: fastify-url-shortner-preview
      autoPromotionEnabled: true
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: main
        image: api:latest
        ports:
        - containerPort: 80
