---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: fastify-url-shortner
    foo: bar
    asdf: asdf
    food: baz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: fastify-url-shortner
        image: fastify-url-shortner:latest
        ports:
        - containerPort: 80