---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    rbac.kargo.akuity.io/claim.groups: 'fdsjal'
  name: pro-writer
  namespace: pro-cool-apps-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pro-writer
  namespace: pro-cool-apps-project
rules:
  - apiGroups:
      - ''
    resources:
      - events
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kargo.akuity.io
    resources:
      - stages
    verbs:
      - patch
      - promote
  - apiGroups:
      - kargo.akuity.io
    resources:
      - promotions
    verbs:
      - patch
      - create
  - apiGroups:
      - kargo.akuity.io
    resources:
      - freights/status
    verbs:
      - patch
  - apiGroups:
      - kargo.akuity.io
    resources:
      - freights
    verbs:
      - patch
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - kargo.akuity.io
    resources:
      - promotions
      - stages
      - warehouses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kargo.akuity.io
    resources:
      - warehouses
    verbs:
      - patch
  - apiGroups:
      - argoproj.io
    resources:
      - analysisruns
      - analysistemplates
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pro-writer
  namespace: pro-cool-apps-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pro-writer
subjects:
  - kind: ServiceAccount
    name: pro-writer
    namespace: pro-cool-apps-project