apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastify-url-shortner-1

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

images:
- name: fastify-url-shortner
  newName: ghcr.io/whereismyjetpack/fastify-url-shortener
  newTag: d299194d4e40795b114eaf74a3424760b250ebbf
patches:
- patch: '[{"op": "replace", "path": "/spec/rules/0/host", "value":"foo-1"}]'
  target:
    kind: Ingress
    name: fastify-url-shortner
