apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastify-url-shortner-2

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

images:
- name: fastify-url-shortner
  newName: ghcr.io/whereismyjetpack/url-shortener
  newTag: ebc0c9b68793aa1fd1481506cd95cbe8856fb2aa
patches:
- patch: '[{"op": "replace", "path": "/spec/rules/0/host", "value":"foo-2"}]'
  target:
    kind: Ingress
    name: fastify-url-shortner
