apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: int
resources:
- deployment.yaml
- service.yaml
images:
- name: api
  newName: 774331681746.dkr.ecr.us-west-2.amazonaws.com/pro-monorepo-api
  newTag: c47d8cc9bc33ccceabe5260fd352cca5297dd60e3