---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: "{{ suite }}-{{ name }}-projectz"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: pro-audit-write-project
  namepsace: pro-audit-write-project
spec:
  promotionPolicies:
  - stageSelector:
      name: "glob:integration*"
    autoPromotionEnabled: true
  - stageSelector:
      name: "glob:staging*"
    autoPromotionEnabled: true
  - stageSelector:
      name: "glob:production*"
    autoPromotionEnabled: false