---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: audit-write-gitops
spec:
  subscriptions:
    - git:
        repoURL: https://whereismyjetpack/gitops.git
        includePaths:
          - kargo/base/resources
          - kargo/base/audit-write
          - kargo/components/audit-write
          - kargo/env/audit-write
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: audit-write-ecr
spec:
  subscriptions:
    - image:
        repoURL: 918073871806.dkr.ecr.us-west-2.amazonaws.com/admin-services/project-name
        allowTags: ^main-.+$
        imageSelectionStrategy: NewestBuild