apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: int
resources:
- deployment.yaml
- service.yaml
images:
- name: fastify-url-shortner
  newName: ghcr.io/whereismyjetpack/url-shortener
  newTag: e0c84b975b2b037d05ec1599c71b2a274e51d386
- name: public.ecr.aws/nginx/nginx
  newTag: 1.27.2
