apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: int
resources:
- deployment.yaml
- service.yaml
images:
- name: fastify-url-shortner
  newName: ghcr.io/whereismyjetpack/url-shortener
  newTag: 51e780c59f625a4cfef3b639605e750af98ee9ea
- name: public.ecr.aws/nginx/nginx
  newTag: 1.27.2
