apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foo

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

images:
- name: fastify-url-shortner
  newName: ghcr.io/whereismyjetpack/url-shortener
  newTag: 92f79095b564f661aaf72ea7e723e5e9c3488593
