apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: int
resources:
- deployment.yaml
- service.yaml
images:
- name: fastify-url-shortner
  newName: public.ecr.aws/nginx/nginx
  newTag: 1.25.0
- name: public.ecr.aws/nginx/nginx
  newTag: 1.27.2
