apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: int
resources:
- deployment.yaml
- service.yaml
images:
- name: fastify-url-shortner
  newName: ghcr.io/whereismyjetpack/url-shortener
  newTag: 7b4dcd072cc2a93ef71766fb9fbb32292989d2e0
- name: public.ecr.aws/nginx/nginx
  newTag: 1.27.2
