apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: int
resources:
- deployment.yaml
- service.yaml
images:
- name: fastify-url-shortner
  newName: ghcr.io/whereismyjetpack/url-shortener
  newTag: 06bc5903210ebb0e55243f8b60ed2c125fe8b7cd
- name: public.ecr.aws/nginx/nginx
  newTag: 1.27.2
