apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: int

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

images:
- name: fastify-url-shortner
  newName: public.ecr.aws/nginx/nginx
  newTag: 1.25.0
