apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastify-url-shortner-preview

resources:
- deployment.yaml

images:
- name: fastify-url-shortner
  newName: ghcr.io/whereismyjetpack/fastify-url-shortener
  newTag: eb9bc72bf7d3777027462df239f4e04485baede7
