apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: int
resources:
- deployment.yaml
- service.yaml
images:
- name: fastify-url-shortner
  newName: ghcr.io/whereismyjetpack/url-shortener
  newTag: b5a893723c4e4e324c0ce72bc04fcf6542ddc4fe
- name: public.ecr.aws/nginx/nginx
  newTag: 1.27.2
