apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foo

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

images:
- name: fastify-url-shortner
  newName: ghcr.io/whereismyjetpack/url-shortener
  newTag: 186284ef40d23a43cf4645499ded37c1a3065e4a
