---
name: Create Kargo Application

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Suite Short Name'
        required: true
        type: string
        default: ''
      name:
        description: 'Name of the Kargo application'
        required: true
      ecr_repo:
        description: 'Full ECR repo name'
        required: true
        type: string
        default: 918073871806.dkr.ecr.us-west-2.amazonaws.com/admin-services/project-name
      gitops_repo:
        description: 'GitOps repo URL'
        required: true
        type: string
        default: 'whereismymetpack/gitops'
      kargo_project_name:
        description: 'Add a parallel pipeline to an existing Kargo project. If not specified, a new project will be created.'
        required: false
        type: string
        default: '{{ suite }}-{{ name }}-project'
      okta_group:
        description: 'Okta group name'
        required: true
        type: string

jobs:
  create-kargo-application:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.gitops_repo }}
          path: gitops

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set Environment Variables
        run: |
          echo "SUITE=${{ github.event.inputs.suite }}" >> $GITHUB_ENV
          echo "NAME=${{ github.event.inputs.name }}" >> $GITHUB_ENV
          echo "OKTA_GROUP=${{ github.event.inputs.okta_group }}" >> $GITHUB_ENV
          echo "ECR_REPO=${{ github.event.inputs.ecr_repo }}" >> $GITHUB_ENV
          echo "GITOPS_REPO=https://${{ github.event.inputs.gitops_repo }}.git" >> $GITHUB_ENV
          echo "KARGO_PROJECT_NAME=${{ github.event.inputs.kargo_project_name }}" >> $GITHUB_ENV

      - name: Create Kargo Application
        id: create-kargo-application
        run: |
          python bin/template.py

      - name: Copy Kargo Application into GitOps Repo
        run: |
          cp -rf rendered/kargo gitops/kargo 

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          path: gitops

      # - name: tmate
      #   uses: mxschmitt/action-tmate@v3