---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  department: rnd
  environment: integration
  service: {{ name }}
  suite: {{ suite}}
  team: {{ name }}

helmCharts:
  - name: application-core
    namespace: ub-integration
    releaseName: {{ name }}
    repo: https://opengov.github.io/helm-charts-external/
    valuesFile: values.yaml
    version: 4.5.2

resources:
  - deployment-metadata.yaml

images:
  - name: {{ ecr_repo }}
    newName: {{ ecr_repo }}
    newTag: kargo-replaces-this